### ISSUE TITLE
It seems that a lot of changes has been made since the zig version of 0.12.0-dev.1835+697b8f7d2.

### ISSUE THREAD

**Issue by ACCodelover** [capy-ui/zig-template#10]
I cloned the zig-template project and run `zig build serve` with the zig version of 0.12.0-dev.2105+60094cc3f. There were many errors, after some checking, I found that most errors were related to the changes of the name of API and the location of API. I tried to change them to the latest version of zig, but there were too many, so I first issued this and see what I can help with.

Here are some APIs that may be changed.
1. `std.build.Builder` -> `std.Build`
2. `addModule` was moved to `std.Build.addModule`.

Anything I can help with please tell me, I would try my best.

**Comment by zenith391** [comment]
closed by fbb15f4a63f0ffbdbcde77bb2ee2eea649f974a3
