### ISSUE TITLE
zig build not wroking on window

### ISSUE THREAD

**Issue by dhrubrawat66** [capy-ui/zig-template#12]
1. zig version -> 0.12.0-dev.2063+804cee3b9
2. when i run the zig build run, It throws following errors
3. 
![Screenshot 2024-07-20 170959](https://github.com/user-attachments/assets/530fb4dd-cc22-42f5-b59f-b7a5d7a7c7f0)

what to do?

**Comment by FableDarkside00** [comment]
Same

**Comment by fable00** [comment]
> 1. zig version -> 0.12.0-dev.2063+804cee3b9
> 2. when i run the zig build run, It throws following errors
> 
> ![Screenshot 2024-07-20 170959](https://private-user-images.githubusercontent.com/85351405/350688445-530fb4dd-cc22-42f5-b59f-b7a5d7a7c7f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MjIyMzMsIm5iZiI6MTcyMTUyMTkzMywicGF0aCI6Ii84NTM1MTQwNS8zNTA2ODg0NDUtNTMwZmI0ZGQtY2MyMi00MmY1LWI1OWYtYjdhNWQ3YTdjN2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDAwMzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZGM5OGI3NzY2NWY2Y2NjNjhkMzY5YjllZDY2NTFlYjYwOTZkMTcxZDk5ZTU0MDE2MzYyZGNhOGJmNDA1OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eiWBBBLC4e5UD8UZGV4vSDEVe2DIf4zy4irqroIndVs)
> 
> what to do?

I solved it by updating the version of zig to 0.13.0-dev.351+64ef45eb0, then changing in (i think the numbers can change) '.cache/zig/p/1220bc2612b57b0cfaaecbcac38e3144e5a9362ff668d71eb8334e895047bdbb7148/build.zig' and in .cache/zig/p/1220c94dbcdf5a799ce2b1571978ff3c97bab1341fe329084fcc3c06e5d6375469b9/build.zig all the lines with
.root_source_file = .path = "some stuff" to .root_source_file = .{ .src_path = .{.owner = b, .sub_path = "the stuff was here"} }. Then installed gtk4 with "sudo apt install libgtk-4-dev", and all worked fine.
