### ISSUE TITLE
Build fail on windows

### ISSUE THREAD

**Issue by NexWan** [capy-ui/zig-template#13]
I'm currently using zig version 0.12.0-dev.2063+804cee3b9, when I try to build and run the project it throws this errors
![image](https://github.com/user-attachments/assets/847c80db-15df-4a16-9d44-21003aee3ff3)

**Comment by NexWan** [comment]
I've already tested using version 0.13.0 and the nominated version, it actually gives me different errors involving deadlocks, cleaned zig global cache yet nothing

**Comment by fable00** [comment]
> I've already tested using version 0.13.0 and the nominated version, it actually gives me different errors involving deadlocks, cleaned zig global cache yet nothing

Yeah but what error specifically appear when u change the version?, and in the error you already got how is the Lazy path function set?

**Comment by NexWan** [comment]
> > I've already tested using version 0.13.0 and the nominated version, it actually gives me different errors involving deadlocks, cleaned zig global cache yet nothing
> 
> Yeah but what error specifically appear when u change the version?, and in the error you already got how is the Lazy path function set?

In version 0.13.0-dev.351+64ef45eb0 this warnings appear first when I build
![image](https://github.com/user-attachments/assets/ff80bfc5-f656-443e-851a-83da6eba161a)
then it's followed by a lot of these kind of errors
![image](https://github.com/user-attachments/assets/7887513d-d623-41f5-bd94-be90e2807a34)
![image](https://github.com/user-attachments/assets/6ef83e61-6da6-445c-82f6-bcf38fe3e7fb)

**Comment by NexWan** [comment]
And about the lazypath, I've run it again with 0.12 nominated version and the error seems to be different for some reason
![image](https://github.com/user-attachments/assets/b3f4d804-a4b2-4997-8301-3dc7c3a48215)

They appear to come from the cache since they go to my global cache directory when the error is being thrown, so maybe the problem is a version when I run it on 0.12 since the build files from the cache says that I should run it on 0.13.0 or the 0.13 nominated version, but when I run it on one of those versions is when the deadlock error appears

**Comment by zenith391** [comment]
The targeted Zig version is `0.13.0` / `2024.5.0-mach` , it won't work with other Zig versions.

**Comment by chadhyatt** [comment]
> The targeted Zig version is `0.13.0` / `2024.5.0-mach` , it won't work with other Zig versions.

I'm on `0.13.0` (Windows x86_64), and I'm also getting the same mutex `Deadlock detected` error as @NexWan:
![image](https://github.com/user-attachments/assets/78581759-fa45-4e71-8a08-da14d998cc40)

This is with just cloning the template repo, not modifying anything at all.

**Comment by chadhyatt** [comment]
Oh just fantastic, it compiles with ReleaseSmall/Fast, but not Debug... 😕

![image](https://github.com/user-attachments/assets/4e2318ed-5817-40e8-bc0d-ad31d2456fd2)

**Comment by NexWan** [comment]
> Oh just fantastic, it compiles with ReleaseSmall/Fast, but not Debug... 😕
> 
> ![image](https://private-user-images.githubusercontent.com/56618074/352305481-4e2318ed-5817-40e8-bc0d-ad31d2456fd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NDczMjQsIm5iZiI6MTcyMTk0NzAyNCwicGF0aCI6Ii81NjYxODA3NC8zNTIzMDU0ODEtNGUyMzE4ZWQtNTgxNy00MGU4LWJjMGQtYWQzMWQyNDU2ZmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDIyMzcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZjdmMWJhOTE0ZGEzZTM2Y2UzZDQ3MmE2MTgwNDE0OGUwNzY5MTg1ODRlNTFiOTNlZTBhMGRhOWI4M2NhOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q0R2hGmlKT-UbfKTb-bjBBrK_4apt_Tk0RxjzPznYA4)

I've just changed it to ReleaseSmall and indeed it worked
![image](https://github.com/user-attachments/assets/a1d93501-4986-422b-a572-b0e17fdb945d)
