### ISSUE TITLE
zig build run not working on window.

### ISSUE THREAD

**Issue by dhrubrawat66** [capy-ui/zig-template#14]
1.  window 11
2. zig version => 0.13.0
3. zig build run throw following error
![Screenshot 2024-08-01 192413](https://github.com/user-attachments/assets/bdbadaf4-7170-41a6-a20f-064f76e97950)

**Comment by zenith391** [comment]
Should now be fixed 19530aa7ba559df3461baf3e6c69f0001b3ef7f0
