### ISSUE TITLE
When using zig build run, an error message is reported

### ISSUE THREAD

**Issue by qcjxberin** [capy-ui/zig-template#15]
When using zig build run, an error message is reported

PS E:\Demo\Zig\CapyDemo> zig build run
error: UnsupportedOs
C:\Users\qcjxb\AppData\Local\zig\p\1220ad9893f583a1c0e3c08f23a58e0846600d1ee854fb916c95678df0a3b4be6dd3\build_capy.zig:272:13: 0xab4f12 in runStep (build.exe.obj)
            return error.UnsupportedOs;
            ^
E:\Demo\Zig\CapyDemo\build.zig:39:19: 0xab59eb in build (build.exe.obj)
    const serve = try build_capy.runStep(wasm, .{});
                  ^
C:\Users\qcjxb\scoop\apps\zig\0.13.0\lib\std\Build.zig:2117:24: 0xa9d969 in runBuild__anon_8953 (build.exe.obj)
        .ErrorUnion => try build_zig.build(b),
                       ^
C:\Users\qcjxb\scoop\apps\zig\0.13.0\lib\compiler\build_runner.zig:301:9: 0xa98e2c in main (build.exe.obj)
        try builder.runBuild(root);

**Comment by zenith391** [comment]
Fixed by 546e3853a90847ab83038b9003495d50d175ed91
