### ISSUE TITLE
ManifestNotFound when trying to init the repo

### ISSUE THREAD

**Issue by gyulanemeth** [capy-ui/zig-template#5]
Hello,

I was gonna try out capy UI, but unfortunately, zigmod fetch did not work on my computer. It gives me the following error:
<img width="1006" alt="Screenshot 2023-08-25 at 10 34 18" src="https://github.com/capy-ui/zig-template/assets/1527824/ef9d8b3d-166b-46ce-9fe3-2d7fdc664681">

What am I doing wrong?

**Comment by zenith391** [comment]
Capy is no longer using Zigmod so that's what causing the problem. It's now using the zig package manager so just skip the `zigmod fetch` step and it'll work. I'll reflect that in the install instructions.
